version: '3.1'
services:
    mysql:
        image: mysql:5.7
        restart: always
        environment:
            MYSQL_DATABASE: 'linkedktu'
            MYSQL_USER: 'dogukanatalay'
            MYSQL_PASSWORD: 'EgWNiTf2WRGUHlOtFWnBPm6ivNmLeIG0'
            MYSQL_ROOT_PASSWORD: 'EgWNiTf2WRGUHlOtFWnBPm6ivNmLeIG0'
        ports:
            - '3306:3306'
        expose:
            - '3306'
        volumes:
            - my-db:/var/lib/mysql
volumes:
    my-db:
